### Sign up a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "dad3@dad.com",
  "password": "Asdf123!",
  "platform": "web"
}

### Confirm email address
Post http://localhost:3000/auth/confirmEmail
Content-Type: application/json

{
  "username": "dad2@dad.com",
  "token": "dc254b438f9da5c6"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "dad@dad.com",
  "password": "Asdf123!",
  "platform": "windows"
}
