### Get All Users
GET http://localhost:3000/api/v1/user/allusers


### Sign up a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "Dad",
  "email": "dad2@dad.com",
  "password": "Asdf123!"
}

### Get user details by ID
GET http://localhost:3000/api/v1/user/6

### Confirm email address
Post http://localhost:3000/auth/confirmEmail
Content-Type: application/json

{
  "email": "dad2@dad.com"
}

### Delete User
DELETE http://localhost:3000/api/user/1
